name: Atualizar INOVA

on:
  schedule:
    - cron: "0 1 * * *"   # 22h no Brasil = 01h UTC
  workflow_dispatch:      # também permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: python agendador.py
